name: Continuous Integration

on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:
    pull_request:

permissions:
    checks: write
    contents: read

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm install

            - name: Formatting
              run: npm run format:check

            - name: Build
              run: npm run build

            - name: Linting
              run: npm run lint

            - name: Unit tests (common)
              run: npx zenfs-test -pfw --common --ci "Unit tests (common)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Unit tests (InMemory)
              run: npx zenfs-test -pfw tests/setup/memory.ts --ci "Unit tests (InMemory)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Unit tests (contexts)
              run: npx zenfs-test -pfw tests/setup/context.ts --ci "Unit tests (contexts)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Unit tests (Index)
              run: npx zenfs-test -pfw tests/setup/index.ts --ci "Unit tests (Index)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Unit tests (Port)
              run: npx zenfs-test -pfw tests/setup/port.ts --ci "Unit tests (Port)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Unit tests (Overlay+Fetch)
              run: tests/fetch/run.sh -w --ci "Unit tests (Overlay+Fetch)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Report coverage
              run: npx zenfs-test --report
